name: module_ekyc
description: "A new Flutter module project."
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

_internal_variables_:
  - &syncfusion_ver "23.2.4"

environment:
  sdk: '>=3.4.0 <4.0.0'

dependency_overrides:
  dio: ^5.4.2+1
  intl: 0.18.0

dependencies:
  another_flushbar: ^1.12.30
  app_settings: ^5.1.1
  asn1lib: ^1.5.3
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.6
  device_info_plus: 9.1.2
  dmrtd:
    git:
      url: https://github.com/HVLoc/dmrtd
      ref: master
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.12.4
  flutter_nfc_kit: 3.4.2
  flutter_pdfview: ^1.2.7
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  flutter_widget_from_html: ^0.15.2
  fluttertoast: ^8.2.5
  get: ^4.6.6
  google_fonts: 6.1.0
  google_mlkit_face_detection: ^0.9.0
  hive: ^2.2.3
  image: ^4.1.3
  image_picker: ^1.0.5
  just_audio: ^0.9.38
  loading_overlay_pro: ^2.1.1
  local_auth: ^2.2.0
  logger: ^2.2.0
  mobile_scanner: ^3.5.2
  nfc_manager: ^3.4.0
  package_info_plus: ^4.2.0
  percent_indicator: ^4.2.3
  permission_handler: ^8.1.6
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  sds_assets_generator:
    git:
      url: https://github.com/toannmdev/sds_assets_generator.git
      ref: master
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # 
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.module_ekyc
    iosBundleIdentifier: com.example.moduleEkyc
  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by SoftDreams Developer
  # **************************************************************************

    - packages/sds_assets/assets/jpg/icon_banner_login.png
    - packages/sds_assets/assets/jpg/icon_faceid.png
    - packages/sds_assets/assets/jpg/icon_fingerprint.png
    - packages/sds_assets/assets/jpg/image_banner.png
    - packages/sds_assets/assets/jpg/image_default.jpg
    - packages/sds_assets/assets/jpg/img_card_cccd.png
    - packages/sds_assets/assets/jpg/img_mail.png
    - packages/sds_assets/assets/locales/vi_VN.json
    - packages/sds_assets/assets/svg/error-svgrepo-com.svg
    - packages/sds_assets/assets/svg/ic_error_snackbar.svg
    - packages/sds_assets/assets/svg/ic_success_snackbar.svg
    - packages/sds_assets/assets/svg/icon_acc_ekyc.svg
    - packages/sds_assets/assets/svg/icon_add_item.svg
    - packages/sds_assets/assets/svg/icon_address.svg
    - packages/sds_assets/assets/svg/icon_appear_eye.svg
    - packages/sds_assets/assets/svg/icon_authentication.svg
    - packages/sds_assets/assets/svg/icon_await_ocr_data.svg
    - packages/sds_assets/assets/svg/icon_back.svg
    - packages/sds_assets/assets/svg/icon_background_payment.svg
    - packages/sds_assets/assets/svg/icon_banner_home.svg
    - packages/sds_assets/assets/svg/icon_banner_login.svg
    - packages/sds_assets/assets/svg/icon_bell.svg
    - packages/sds_assets/assets/svg/icon_birthday.svg
    - packages/sds_assets/assets/svg/icon_border_qr.svg
    - packages/sds_assets/assets/svg/icon_border_top_left.svg
    - packages/sds_assets/assets/svg/icon_border_top_left_cap.svg
    - packages/sds_assets/assets/svg/icon_button_qr.svg
    - packages/sds_assets/assets/svg/icon_button_retake.svg
    - packages/sds_assets/assets/svg/icon_calender.svg
    - packages/sds_assets/assets/svg/icon_cancel.svg
    - packages/sds_assets/assets/svg/icon_cancel_authentication.svg
    - packages/sds_assets/assets/svg/icon_canlendar_card.svg
    - packages/sds_assets/assets/svg/icon_card_cccd.svg
    - packages/sds_assets/assets/svg/icon_card_info.svg
    - packages/sds_assets/assets/svg/icon_checkmark.svg
    - packages/sds_assets/assets/svg/icon_circle.svg
    - packages/sds_assets/assets/svg/icon_client.svg
    - packages/sds_assets/assets/svg/icon_close.svg
    - packages/sds_assets/assets/svg/icon_company.svg
    - packages/sds_assets/assets/svg/icon_contract.svg
    - packages/sds_assets/assets/svg/icon_corner_left_down.png
    - packages/sds_assets/assets/svg/icon_corner_left_up.png
    - packages/sds_assets/assets/svg/icon_corner_right_down.png
    - packages/sds_assets/assets/svg/icon_corner_right_up.png
    - packages/sds_assets/assets/svg/icon_create_folder.svg
    - packages/sds_assets/assets/svg/icon_delete.svg
    - packages/sds_assets/assets/svg/icon_direction.svg
    - packages/sds_assets/assets/svg/icon_done.svg
    - packages/sds_assets/assets/svg/icon_email.svg
    - packages/sds_assets/assets/svg/icon_email_support.svg
    - packages/sds_assets/assets/svg/icon_face_between.svg
    - packages/sds_assets/assets/svg/icon_face_blink.svg
    - packages/sds_assets/assets/svg/icon_face_down.svg
    - packages/sds_assets/assets/svg/icon_face_left.svg
    - packages/sds_assets/assets/svg/icon_face_right.svg
    - packages/sds_assets/assets/svg/icon_face_smile.svg
    - packages/sds_assets/assets/svg/icon_face_up.svg
    - packages/sds_assets/assets/svg/icon_faceid.svg
    - packages/sds_assets/assets/svg/icon_fingerprint.svg
    - packages/sds_assets/assets/svg/icon_flash.svg
    - packages/sds_assets/assets/svg/icon_flash_off.svg
    - packages/sds_assets/assets/svg/icon_gender.svg
    - packages/sds_assets/assets/svg/icon_globe.svg
    - packages/sds_assets/assets/svg/icon_hidden_eye.svg
    - packages/sds_assets/assets/svg/icon_home.svg
    - packages/sds_assets/assets/svg/icon_home_authentication.svg
    - packages/sds_assets/assets/svg/icon_home_authentication_focus.svg
    - packages/sds_assets/assets/svg/icon_home_focus.svg
    - packages/sds_assets/assets/svg/icon_home_list_user.svg
    - packages/sds_assets/assets/svg/icon_home_list_user_focus.svg
    - packages/sds_assets/assets/svg/icon_home_other.svg
    - packages/sds_assets/assets/svg/icon_home_service_package.svg
    - packages/sds_assets/assets/svg/icon_home_service_package_focus.svg
    - packages/sds_assets/assets/svg/icon_hotline.svg
    - packages/sds_assets/assets/svg/icon_instruct_live_ness.svg
    - packages/sds_assets/assets/svg/icon_item_buy_home.svg
    - packages/sds_assets/assets/svg/icon_item_extend_home_home.svg
    - packages/sds_assets/assets/svg/icon_item_home.svg
    - packages/sds_assets/assets/svg/icon_item_info_home.svg
    - packages/sds_assets/assets/svg/icon_item_kyc.svg
    - packages/sds_assets/assets/svg/icon_item_mission_home.svg
    - packages/sds_assets/assets/svg/icon_item_recall_home.svg
    - packages/sds_assets/assets/svg/icon_kyc.svg
    - packages/sds_assets/assets/svg/icon_kyc_login.svg
    - packages/sds_assets/assets/svg/icon_kyc_small.svg
    - packages/sds_assets/assets/svg/icon_list.svg
    - packages/sds_assets/assets/svg/icon_list_cts.svg
    - packages/sds_assets/assets/svg/icon_list_document_item_home.svg
    - packages/sds_assets/assets/svg/icon_list_document_not_confirm_item_home.svg
    - packages/sds_assets/assets/svg/icon_list_null.svg
    - packages/sds_assets/assets/svg/icon_list_user.svg
    - packages/sds_assets/assets/svg/icon_live_ness.svg
    - packages/sds_assets/assets/svg/icon_load_err.svg
    - packages/sds_assets/assets/svg/icon_lock.svg
    - packages/sds_assets/assets/svg/icon_logo_support.svg
    - packages/sds_assets/assets/svg/icon_logout.svg
    - packages/sds_assets/assets/svg/icon_map.svg
    - packages/sds_assets/assets/svg/icon_more_home.svg
    - packages/sds_assets/assets/svg/icon_nationality.svg
    - packages/sds_assets/assets/svg/icon_nfc.svg
    - packages/sds_assets/assets/svg/icon_nfc_connect.svg
    - packages/sds_assets/assets/svg/icon_nfc_home_town.svg
    - packages/sds_assets/assets/svg/icon_nfc_identifying_signs.svg
    - packages/sds_assets/assets/svg/icon_nfc_nation.svg
    - packages/sds_assets/assets/svg/icon_no_support_nfc.svg
    - packages/sds_assets/assets/svg/icon_noti_bell.svg
    - packages/sds_assets/assets/svg/icon_noti_success.svg
    - packages/sds_assets/assets/svg/icon_notification.svg
    - packages/sds_assets/assets/svg/icon_notification_home.svg
    - packages/sds_assets/assets/svg/icon_notification_home_focus.svg
    - packages/sds_assets/assets/svg/icon_number_phone.svg
    - packages/sds_assets/assets/svg/icon_other_user.svg
    - packages/sds_assets/assets/svg/icon_package.svg
    - packages/sds_assets/assets/svg/icon_package_card.svg
    - packages/sds_assets/assets/svg/icon_pass.svg
    - packages/sds_assets/assets/svg/icon_register_kyc.svg
    - packages/sds_assets/assets/svg/icon_scan_nfc.svg
    - packages/sds_assets/assets/svg/icon_search.svg
    - packages/sds_assets/assets/svg/icon_service_ca.svg
    - packages/sds_assets/assets/svg/icon_service_package.svg
    - packages/sds_assets/assets/svg/icon_success.svg
    - packages/sds_assets/assets/svg/icon_support.svg
    - packages/sds_assets/assets/svg/icon_support_nfc.svg
    - packages/sds_assets/assets/svg/icon_tag.svg
    - packages/sds_assets/assets/svg/icon_take_picture.svg
    - packages/sds_assets/assets/svg/icon_telephone.svg
    - packages/sds_assets/assets/svg/icon_user.svg
    - packages/sds_assets/assets/svg/icon_user_name_card.svg
    - packages/sds_assets/assets/svg/icon_warning.svg
    - packages/sds_assets/assets/svg/icon_web.svg
    - packages/sds_assets/assets/svg/notification-13-svgrepo-com.svg
    - packages/sds_assets/assets/svg/success-standard-svgrepo-com.svg
    - packages/sds_assets/assets/svg/warning-svgrepo-com.svg

  # assets end