// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String LIB_ASSETS_DART = 'lib/assets.dart';

  static const String LIB_ASSETS_PREVIEW_DART = 'lib/assets.preview.dart';

  /// {@macro assets_generator.LIB_ASSETS_JPG_ICON_BANNER_LOGIN_PNG.preview}
  static const String LIB_ASSETS_JPG_ICON_BANNER_LOGIN_PNG =
      'lib/assets/jpg/icon_banner_login.png';

  /// {@macro assets_generator.LIB_ASSETS_JPG_ICON_FACEID_PNG.preview}
  static const String LIB_ASSETS_JPG_ICON_FACEID_PNG =
      'lib/assets/jpg/icon_faceid.png';

  /// {@macro assets_generator.LIB_ASSETS_JPG_ICON_FINGERPRINT_PNG.preview}
  static const String LIB_ASSETS_JPG_ICON_FINGERPRINT_PNG =
      'lib/assets/jpg/icon_fingerprint.png';

  /// {@macro assets_generator.LIB_ASSETS_JPG_IMAGE_BANNER_PNG.preview}
  static const String LIB_ASSETS_JPG_IMAGE_BANNER_PNG =
      'lib/assets/jpg/image_banner.png';

  /// {@macro assets_generator.LIB_ASSETS_JPG_IMAGE_DEFAULT_JPG.preview}
  static const String LIB_ASSETS_JPG_IMAGE_DEFAULT_JPG =
      'lib/assets/jpg/image_default.jpg';

  /// {@macro assets_generator.LIB_ASSETS_JPG_IMG_CARD_CCCD_PNG.preview}
  static const String LIB_ASSETS_JPG_IMG_CARD_CCCD_PNG =
      'lib/assets/jpg/img_card_cccd.png';

  /// {@macro assets_generator.LIB_ASSETS_JPG_IMG_MAIL_PNG.preview}
  static const String LIB_ASSETS_JPG_IMG_MAIL_PNG =
      'lib/assets/jpg/img_mail.png';

  static const String LIB_ASSETS_LOCALES_VI_VN_JSON =
      'lib/assets/locales/vi_VN.json';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ERROR_SVGREPO_COM_SVG.preview}
  static const String LIB_ASSETS_SVG_ERROR_SVGREPO_COM_SVG =
      'lib/assets/svg/error-svgrepo-com.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_IC_ERROR_SNACKBAR_SVG.preview}
  static const String LIB_ASSETS_SVG_IC_ERROR_SNACKBAR_SVG =
      'lib/assets/svg/ic_error_snackbar.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
  static const String LIB_ASSETS_SVG_IC_SUCCESS_SNACKBAR_SVG =
      'lib/assets/svg/ic_success_snackbar.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ACC_EKYC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ACC_EKYC_SVG =
      'lib/assets/svg/icon_acc_ekyc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ADD_ITEM_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ADD_ITEM_SVG =
      'lib/assets/svg/icon_add_item.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ADDRESS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ADDRESS_SVG =
      'lib/assets/svg/icon_address.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_APPEAR_EYE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_APPEAR_EYE_SVG =
      'lib/assets/svg/icon_appear_eye.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_AUTHENTICATION_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_AUTHENTICATION_SVG =
      'lib/assets/svg/icon_authentication.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG =
      'lib/assets/svg/icon_await_ocr_data.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BACK_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BACK_SVG =
      'lib/assets/svg/icon_back.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BACKGROUND_PAYMENT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BACKGROUND_PAYMENT_SVG =
      'lib/assets/svg/icon_background_payment.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BANNER_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BANNER_HOME_SVG =
      'lib/assets/svg/icon_banner_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BANNER_LOGIN_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BANNER_LOGIN_SVG =
      'lib/assets/svg/icon_banner_login.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BELL_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BELL_SVG =
      'lib/assets/svg/icon_bell.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BIRTHDAY_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BIRTHDAY_SVG =
      'lib/assets/svg/icon_birthday.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BORDER_QR_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BORDER_QR_SVG =
      'lib/assets/svg/icon_border_qr.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG =
      'lib/assets/svg/icon_border_top_left.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG =
      'lib/assets/svg/icon_border_top_left_cap.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BUTTON_QR_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BUTTON_QR_SVG =
      'lib/assets/svg/icon_button_qr.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_BUTTON_RETAKE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_BUTTON_RETAKE_SVG =
      'lib/assets/svg/icon_button_retake.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CALENDER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CALENDER_SVG =
      'lib/assets/svg/icon_calender.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CANCEL_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CANCEL_SVG =
      'lib/assets/svg/icon_cancel.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CANCEL_AUTHENTICATION_SVG =
      'lib/assets/svg/icon_cancel_authentication.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CANLENDAR_CARD_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CANLENDAR_CARD_SVG =
      'lib/assets/svg/icon_canlendar_card.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CARD_CCCD_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CARD_CCCD_SVG =
      'lib/assets/svg/icon_card_cccd.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CARD_INFO_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CARD_INFO_SVG =
      'lib/assets/svg/icon_card_info.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CHECKMARK_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CHECKMARK_SVG =
      'lib/assets/svg/icon_checkmark.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CIRCLE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CIRCLE_SVG =
      'lib/assets/svg/icon_circle.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CLIENT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CLIENT_SVG =
      'lib/assets/svg/icon_client.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CLOSE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CLOSE_SVG =
      'lib/assets/svg/icon_close.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_COMPANY_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_COMPANY_SVG =
      'lib/assets/svg/icon_company.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CONTRACT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CONTRACT_SVG =
      'lib/assets/svg/icon_contract.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG.preview}
  static const String LIB_ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG =
      'lib/assets/svg/icon_corner_left_down.png';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG.preview}
  static const String LIB_ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG =
      'lib/assets/svg/icon_corner_left_up.png';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
  static const String LIB_ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG =
      'lib/assets/svg/icon_corner_right_down.png';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG.preview}
  static const String LIB_ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG =
      'lib/assets/svg/icon_corner_right_up.png';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_CREATE_FOLDER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_CREATE_FOLDER_SVG =
      'lib/assets/svg/icon_create_folder.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_DELETE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_DELETE_SVG =
      'lib/assets/svg/icon_delete.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_DIRECTION_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_DIRECTION_SVG =
      'lib/assets/svg/icon_direction.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_DONE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_DONE_SVG =
      'lib/assets/svg/icon_done.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_EMAIL_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_EMAIL_SVG =
      'lib/assets/svg/icon_email.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_EMAIL_SUPPORT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_EMAIL_SUPPORT_SVG =
      'lib/assets/svg/icon_email_support.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACE_BETWEEN_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACE_BETWEEN_SVG =
      'lib/assets/svg/icon_face_between.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACE_BLINK_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACE_BLINK_SVG =
      'lib/assets/svg/icon_face_blink.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACE_DOWN_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACE_DOWN_SVG =
      'lib/assets/svg/icon_face_down.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACE_LEFT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACE_LEFT_SVG =
      'lib/assets/svg/icon_face_left.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACE_RIGHT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACE_RIGHT_SVG =
      'lib/assets/svg/icon_face_right.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACE_SMILE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACE_SMILE_SVG =
      'lib/assets/svg/icon_face_smile.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACE_UP_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACE_UP_SVG =
      'lib/assets/svg/icon_face_up.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FACEID_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FACEID_SVG =
      'lib/assets/svg/icon_faceid.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FINGERPRINT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FINGERPRINT_SVG =
      'lib/assets/svg/icon_fingerprint.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FLASH_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FLASH_SVG =
      'lib/assets/svg/icon_flash.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_FLASH_OFF_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_FLASH_OFF_SVG =
      'lib/assets/svg/icon_flash_off.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_GENDER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_GENDER_SVG =
      'lib/assets/svg/icon_gender.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_GLOBE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_GLOBE_SVG =
      'lib/assets/svg/icon_globe.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HIDDEN_EYE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HIDDEN_EYE_SVG =
      'lib/assets/svg/icon_hidden_eye.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_SVG =
      'lib/assets/svg/icon_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_AUTHENTICATION_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_AUTHENTICATION_SVG =
      'lib/assets/svg/icon_home_authentication.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_AUTHENTICATION_FOCUS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_AUTHENTICATION_FOCUS_SVG =
      'lib/assets/svg/icon_home_authentication_focus.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_FOCUS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_FOCUS_SVG =
      'lib/assets/svg/icon_home_focus.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_LIST_USER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_LIST_USER_SVG =
      'lib/assets/svg/icon_home_list_user.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_LIST_USER_FOCUS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_LIST_USER_FOCUS_SVG =
      'lib/assets/svg/icon_home_list_user_focus.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_OTHER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_OTHER_SVG =
      'lib/assets/svg/icon_home_other.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_SVG =
      'lib/assets/svg/icon_home_service_package.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_FOCUS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOME_SERVICE_PACKAGE_FOCUS_SVG =
      'lib/assets/svg/icon_home_service_package_focus.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_HOTLINE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_HOTLINE_SVG =
      'lib/assets/svg/icon_hotline.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG =
      'lib/assets/svg/icon_instruct_live_ness.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG =
      'lib/assets/svg/icon_item_buy_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG =
      'lib/assets/svg/icon_item_extend_home_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ITEM_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ITEM_HOME_SVG =
      'lib/assets/svg/icon_item_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG =
      'lib/assets/svg/icon_item_info_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ITEM_KYC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ITEM_KYC_SVG =
      'lib/assets/svg/icon_item_kyc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG =
      'lib/assets/svg/icon_item_mission_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG =
      'lib/assets/svg/icon_item_recall_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_KYC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_KYC_SVG =
      'lib/assets/svg/icon_kyc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_KYC_LOGIN_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_KYC_LOGIN_SVG =
      'lib/assets/svg/icon_kyc_login.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_KYC_SMALL_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_KYC_SMALL_SVG =
      'lib/assets/svg/icon_kyc_small.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LIST_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LIST_SVG =
      'lib/assets/svg/icon_list.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LIST_CTS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LIST_CTS_SVG =
      'lib/assets/svg/icon_list_cts.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG =
      'lib/assets/svg/icon_list_document_item_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG.preview}
  static const String
      LIB_ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG =
      'lib/assets/svg/icon_list_document_not_confirm_item_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LIST_NULL_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LIST_NULL_SVG =
      'lib/assets/svg/icon_list_null.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LIST_USER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LIST_USER_SVG =
      'lib/assets/svg/icon_list_user.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LIVE_NESS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LIVE_NESS_SVG =
      'lib/assets/svg/icon_live_ness.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LOAD_ERR_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LOAD_ERR_SVG =
      'lib/assets/svg/icon_load_err.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LOCK_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LOCK_SVG =
      'lib/assets/svg/icon_lock.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LOGO_SUPPORT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LOGO_SUPPORT_SVG =
      'lib/assets/svg/icon_logo_support.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_LOGOUT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_LOGOUT_SVG =
      'lib/assets/svg/icon_logout.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_MAP_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_MAP_SVG =
      'lib/assets/svg/icon_map.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_MORE_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_MORE_HOME_SVG =
      'lib/assets/svg/icon_more_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NATIONALITY_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NATIONALITY_SVG =
      'lib/assets/svg/icon_nationality.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NFC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NFC_SVG =
      'lib/assets/svg/icon_nfc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NFC_CONNECT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NFC_CONNECT_SVG =
      'lib/assets/svg/icon_nfc_connect.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG =
      'lib/assets/svg/icon_nfc_home_town.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG =
      'lib/assets/svg/icon_nfc_identifying_signs.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NFC_NATION_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NFC_NATION_SVG =
      'lib/assets/svg/icon_nfc_nation.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG =
      'lib/assets/svg/icon_no_support_nfc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NOTI_BELL_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NOTI_BELL_SVG =
      'lib/assets/svg/icon_noti_bell.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NOTI_SUCCESS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NOTI_SUCCESS_SVG =
      'lib/assets/svg/icon_noti_success.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NOTIFICATION_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NOTIFICATION_SVG =
      'lib/assets/svg/icon_notification.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NOTIFICATION_HOME_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NOTIFICATION_HOME_SVG =
      'lib/assets/svg/icon_notification_home.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NOTIFICATION_HOME_FOCUS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NOTIFICATION_HOME_FOCUS_SVG =
      'lib/assets/svg/icon_notification_home_focus.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_NUMBER_PHONE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_NUMBER_PHONE_SVG =
      'lib/assets/svg/icon_number_phone.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_OTHER_USER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_OTHER_USER_SVG =
      'lib/assets/svg/icon_other_user.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_PACKAGE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_PACKAGE_SVG =
      'lib/assets/svg/icon_package.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_PACKAGE_CARD_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_PACKAGE_CARD_SVG =
      'lib/assets/svg/icon_package_card.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_PASS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_PASS_SVG =
      'lib/assets/svg/icon_pass.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_REGISTER_KYC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_REGISTER_KYC_SVG =
      'lib/assets/svg/icon_register_kyc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_SCAN_NFC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_SCAN_NFC_SVG =
      'lib/assets/svg/icon_scan_nfc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_SEARCH_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_SEARCH_SVG =
      'lib/assets/svg/icon_search.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_SERVICE_CA_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_SERVICE_CA_SVG =
      'lib/assets/svg/icon_service_ca.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_SERVICE_PACKAGE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_SERVICE_PACKAGE_SVG =
      'lib/assets/svg/icon_service_package.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_SUCCESS_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_SUCCESS_SVG =
      'lib/assets/svg/icon_success.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_SUPPORT_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_SUPPORT_SVG =
      'lib/assets/svg/icon_support.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_SUPPORT_NFC_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_SUPPORT_NFC_SVG =
      'lib/assets/svg/icon_support_nfc.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_TAG_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_TAG_SVG =
      'lib/assets/svg/icon_tag.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_TAKE_PICTURE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_TAKE_PICTURE_SVG =
      'lib/assets/svg/icon_take_picture.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_TELEPHONE_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_TELEPHONE_SVG =
      'lib/assets/svg/icon_telephone.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_USER_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_USER_SVG =
      'lib/assets/svg/icon_user.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_USER_NAME_CARD_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_USER_NAME_CARD_SVG =
      'lib/assets/svg/icon_user_name_card.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_WARNING_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_WARNING_SVG =
      'lib/assets/svg/icon_warning.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_ICON_WEB_SVG.preview}
  static const String LIB_ASSETS_SVG_ICON_WEB_SVG =
      'lib/assets/svg/icon_web.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
  static const String LIB_ASSETS_SVG_NOTIFICATION_13_SVGREPO_COM_SVG =
      'lib/assets/svg/notification-13-svgrepo-com.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
  static const String LIB_ASSETS_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG =
      'lib/assets/svg/success-standard-svgrepo-com.svg';

  /// {@macro assets_generator.LIB_ASSETS_SVG_WARNING_SVGREPO_COM_SVG.preview}
  static const String LIB_ASSETS_SVG_WARNING_SVGREPO_COM_SVG =
      'lib/assets/svg/warning-svgrepo-com.svg';

  static const String LIB_BASE_APP_BASE_APP_SRC_DART =
      'lib/base_app/base_app.src.dart';

  static const String
      LIB_BASE_APP_CONTROLLERS_BASE_APP_CONTROLLER_APP_CONTROLLER_DART =
      'lib/base_app/controllers_base/app_controller/app_controller.dart';

  static const String LIB_BASE_APP_CONTROLLERS_BASE_BASE_CONTROLLER_SRC_DART =
      'lib/base_app/controllers_base/base_controller.src.dart';

  static const String
      LIB_BASE_APP_CONTROLLERS_BASE_BASE_CONTROLLER_BASE_CONTROLLER_DART =
      'lib/base_app/controllers_base/base_controller/base_controller.dart';

  static const String
      LIB_BASE_APP_CONTROLLERS_BASE_BASE_CONTROLLER_BASE_CONTROLLER_SRC_DART =
      'lib/base_app/controllers_base/base_controller/base_controller.src.dart';

  static const String
      LIB_BASE_APP_CONTROLLERS_BASE_BASE_CONTROLLER_BASE_REFRESH_CONTROLLER_DART =
      'lib/base_app/controllers_base/base_controller/base_refresh_controller.dart';

  static const String LIB_BASE_APP_MODEL_BASE_LIST_RESPONSE_DART =
      'lib/base_app/model/base_list_response.dart';

  static const String LIB_BASE_APP_MODEL_BASE_RESPONSE_DART =
      'lib/base_app/model/base_response.dart';

  static const String LIB_BASE_APP_MODEL_BASE_RESPONSE_SDK_DART =
      'lib/base_app/model/base_response_sdk.dart';

  static const String LIB_BASE_APP_MODEL_ERROR_BASE_RESPONSE_DART =
      'lib/base_app/model/error_base_response.dart';

  static const String LIB_BASE_APP_MODEL_MODEL_SRC_DART =
      'lib/base_app/model/model.src.dart';

  static const String LIB_BASE_APP_REPOSITORY_BASE_BASE_API_DART =
      'lib/base_app/repository_base/base_api.dart';

  static const String LIB_BASE_APP_REPOSITORY_BASE_BASE_REPOSITORY_DART =
      'lib/base_app/repository_base/base_repository.dart';

  static const String LIB_BASE_APP_REPOSITORY_BASE_REPOSITORY_BASE_SRC_DART =
      'lib/base_app/repository_base/repository_base.src.dart';

  static const String LIB_BASE_APP_VIEWS_BASE_BASE_WIDGET_DART =
      'lib/base_app/views_base/base_widget.dart';

  static const String LIB_BASE_APP_VIEWS_BASE_VIEWS_BASE_SRC_DART =
      'lib/base_app/views_base/views_base.src.dart';

  static const String LIB_CONST_DART = 'lib/const.dart';

  static const String LIB_CORE_CORE_SRC_DART = 'lib/core/core.src.dart';

  static const String LIB_CORE_ENUM_ENUM_SRC_DART =
      'lib/core/enum/enum.src.dart';

  static const String LIB_CORE_ENUM_ENUM_REQUEST_METHOD_DART =
      'lib/core/enum/enum_request_method.dart';

  static const String LIB_CORE_ENUM_ENUM_STATUS_RESPONSE_DART =
      'lib/core/enum/enum_status_response.dart';

  static const String LIB_CORE_ROUTER_APP_ROUTE_DART =
      'lib/core/router/app_route.dart';

  static const String LIB_CORE_ROUTER_APP_ROUTER_SRC_DART =
      'lib/core/router/app_router.src.dart';

  static const String LIB_CORE_ROUTER_ROUTER_PAGE_DART =
      'lib/core/router/router_page.dart';

  static const String LIB_CORE_THEME_APP_THEME_DART =
      'lib/core/theme/app_theme.dart';

  static const String LIB_CORE_THEME_COLORS_DART = 'lib/core/theme/colors.dart';

  static const String LIB_CORE_THEME_THEME_SRC_DART =
      'lib/core/theme/theme.src.dart';

  static const String LIB_CORE_THEME_THEME_WIDGET_SLIDE_DART =
      'lib/core/theme/theme_widget_slide.dart';

  static const String LIB_CORE_VALUES_APP_API_DART =
      'lib/core/values/app_api.dart';

  static const String LIB_CORE_VALUES_COLLECTION_DART =
      'lib/core/values/collection.dart';

  static const String LIB_CORE_VALUES_CONST_DART = 'lib/core/values/const.dart';

  static const String LIB_CORE_VALUES_DIMENS_DART =
      'lib/core/values/dimens.dart';

  static const String LIB_CORE_VALUES_KEY_DART = 'lib/core/values/key.dart';

  static const String LIB_CORE_VALUES_VALUES_SRC_DART =
      'lib/core/values/values.src.dart';

  static const String LIB_GENERATED_LOCALES_G_DART =
      'lib/generated/locales.g.dart';

  static const String
      LIB_HIVE_HELPER_FIELDS_LOGIN_CA_REQUEST_MODEL_FIELDS_DART =
      'lib/hive_helper/fields/login_ca_request_model_fields.dart';

  static const String LIB_HIVE_HELPER_HIVE_ADAPTERS_DART =
      'lib/hive_helper/hive_adapters.dart';

  static const String LIB_HIVE_HELPER_HIVE_TYPES_DART =
      'lib/hive_helper/hive_types.dart';

  static const String LIB_HIVE_HELPER_REGISTER_ADAPTERS_DART =
      'lib/hive_helper/register_adapters.dart';

  static const String LIB_MAIN_DART = 'lib/main.dart';

  static const String LIB_MAIN2_DART = 'lib/main2.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_CHANGE_PASSWORD_CHANGE_PASSWORD_SRC_DART =
      'lib/modules/authentication_kyc/change_password/change_password.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_CHANGE_PASSWORD_CONTROLLERS_CHANGE_PASSWORD_CONTROLLER_DART =
      'lib/modules/authentication_kyc/change_password/controllers/change_password_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_CHANGE_PASSWORD_VIEWS_CHANGE_PASSWORD_PAGE_DART =
      'lib/modules/authentication_kyc/change_password/views/change_password_page.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_CHANGE_PASSWORD_VIEWS_CHANGE_PASSWORD_VIEW_DART =
      'lib/modules/authentication_kyc/change_password/views/change_password_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FACE_MATCHING_RESULT_CONTROLLERS_FACE_MATCHING_RESULT_CONTROLLER_DART =
      'lib/modules/authentication_kyc/face_matching_result/controllers/face_matching_result_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FACE_MATCHING_RESULT_FACE_MATCHING_RESULT_SRC_DART =
      'lib/modules/authentication_kyc/face_matching_result/face_matching_result.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FACE_MATCHING_RESULT_VIEWS_FACE_MATCHING_RESULT_PAGE_DART =
      'lib/modules/authentication_kyc/face_matching_result/views/face_matching_result_page.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FACE_MATCHING_RESULT_VIEWS_FACE_MATCHING_RESULT_VIEW_DART =
      'lib/modules/authentication_kyc/face_matching_result/views/face_matching_result_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FORGOT_PASSWORD_CONTROLLERS_FORGOT_PASSWORD_CONTROLLER_DART =
      'lib/modules/authentication_kyc/forgot_password/controllers/forgot_password_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FORGOT_PASSWORD_FORGOT_PASSWORD_SRC_DART =
      'lib/modules/authentication_kyc/forgot_password/forgot_password.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FORGOT_PASSWORD_REPOSITORY_FORGOT_PASSWORD_REPOSITORY_DART =
      'lib/modules/authentication_kyc/forgot_password/repository/forgot_password_repository.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FORGOT_PASSWORD_VIEWS_FORGOT_PASSWORD_PAGE_DART =
      'lib/modules/authentication_kyc/forgot_password/views/forgot_password_page.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_FORGOT_PASSWORD_VIEWS_FORGOT_PASSWORD_VIEW_DART =
      'lib/modules/authentication_kyc/forgot_password/views/forgot_password_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_COLLECTION_LIVE_NESS_COLLECTION_DART =
      'lib/modules/authentication_kyc/live_ness/collection/live_ness_collection.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_CONTROLLERS_LIVE_NESS_KYC_CONTROLLER_DART =
      'lib/modules/authentication_kyc/live_ness/controllers/live_ness_kyc_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_DETECTION_LIVENESS_DETECTOR_DART =
      'lib/modules/authentication_kyc/live_ness/detection/liveness_detector.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_LIVE_NESS_KYC_SRC_DART =
      'lib/modules/authentication_kyc/live_ness/live_ness_kyc.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_MODEL_FACE_MATCHING_RESPONSE_DART =
      'lib/modules/authentication_kyc/live_ness/model/face_matching_response.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_MODEL_FACE_MATCHING_SDK_RESPONSE_DART =
      'lib/modules/authentication_kyc/live_ness/model/face_matching_sdk_response.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_MODEL_LIVE_NESS_DETECTION_MODEL_DART =
      'lib/modules/authentication_kyc/live_ness/model/live_ness_detection_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_MODEL_LIVE_NESS_INFO_MODEL_DART =
      'lib/modules/authentication_kyc/live_ness/model/live_ness_info_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_MODEL_LIVE_NESS_REQUEST_MODEL_DART =
      'lib/modules/authentication_kyc/live_ness/model/live_ness_request_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_MODEL_LIVENESS_MODEL_SRC_DART =
      'lib/modules/authentication_kyc/live_ness/model/liveness_model.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_PAINTER_PAINTER_LIVE_NESS_DART =
      'lib/modules/authentication_kyc/live_ness/painter/painter_live_ness.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_REPOSITORY_LIVE_NESS_REPOSITORY_DART =
      'lib/modules/authentication_kyc/live_ness/repository/live_ness_repository.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_VIEWS_LIVE_NESS_PAGE_LIVE_NESS_KYC_PAGE_DART =
      'lib/modules/authentication_kyc/live_ness/views/live_ness_page/live_ness_kyc_page.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_LIVE_NESS_VIEWS_LIVE_NESS_PAGE_LIVE_NESS_KYC_VIEW_DART =
      'lib/modules/authentication_kyc/live_ness/views/live_ness_page/live_ness_kyc_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_INFORMATION_USER_CONTROLLERS_NFC_INFORMATION_USER_CONTROLLER_DART =
      'lib/modules/authentication_kyc/nfc_information_user/controllers/nfc_information_user_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_INFORMATION_USER_NFC_INFORMATION_USER_SRC_DART =
      'lib/modules/authentication_kyc/nfc_information_user/nfc_information_user_src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_INFORMATION_USER_VIEWS_NFC_INFORMATION_USER_PAGE_DART =
      'lib/modules/authentication_kyc/nfc_information_user/views/nfc_information_user_page.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_INFORMATION_USER_VIEWS_NFC_INFORMATION_USER_VIEW_DART =
      'lib/modules/authentication_kyc/nfc_information_user/views/nfc_information_user_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_CONTROLLERS_NFC_KYC_CONTROLLER_DART =
      'lib/modules/authentication_kyc/nfc_kyc/controllers/nfc_kyc_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_MODEL_NFC_MRTD_DATA_DART =
      'lib/modules/authentication_kyc/nfc_kyc/model/nfc_mrtd_data.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_MODEL_NFC_REQUEST_MODEL_DART =
      'lib/modules/authentication_kyc/nfc_kyc/model/nfc_request_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_MODEL_NFC_RESPONSE_MODEL_DART =
      'lib/modules/authentication_kyc/nfc_kyc/model/nfc_response_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_MODEL_VERIFY_SDK_RESPONSE_DART =
      'lib/modules/authentication_kyc/nfc_kyc/model/verify_sdk_response.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_NFC_DIALOG_NFC_DIALOG_DART =
      'lib/modules/authentication_kyc/nfc_kyc/nfc_dialog/nfc_dialog.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_NFC_DIALOG_NFC_DIALOG_SRC_DART =
      'lib/modules/authentication_kyc/nfc_kyc/nfc_dialog/nfc_dialog.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_NFC_DIALOG_NFC_DIALOG_CONTROLLER_DART =
      'lib/modules/authentication_kyc/nfc_kyc/nfc_dialog/nfc_dialog_controller.dart';

  static const String LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_NFC_KYC_SRC_DART =
      'lib/modules/authentication_kyc/nfc_kyc/nfc_kyc.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_REPOSITORY_NFC_REPOSITORY_DART =
      'lib/modules/authentication_kyc/nfc_kyc/repository/nfc_repository.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_VIEWS_NFC_KYC_PAGE_DART =
      'lib/modules/authentication_kyc/nfc_kyc/views/nfc_kyc_page.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_NFC_KYC_VIEWS_NFC_KYC_VIEW_DART =
      'lib/modules/authentication_kyc/nfc_kyc/views/nfc_kyc_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_QR_KYC_CONTROLLERS_QR_CONTROLLER_DART =
      'lib/modules/authentication_kyc/qr_kyc/controllers/qr_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_QR_KYC_MODEL_QR_USER_INFORMATION_DART =
      'lib/modules/authentication_kyc/qr_kyc/model/qr_user_information.dart';

  static const String LIB_MODULES_AUTHENTICATION_KYC_QR_KYC_QR_KYC_SRC_DART =
      'lib/modules/authentication_kyc/qr_kyc/qr_kyc.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_QR_KYC_VIEWS_QR_GUIDE_DART =
      'lib/modules/authentication_kyc/qr_kyc/views/qr_guide.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_COLLECTION_SERVICE_TYPE_ENUM_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/collection/service_type_enum.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_CONTROLLERS_AUTHENTICATION_GUIDE_CONTROLLER_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/controllers/authentication_guide_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_CONTROLLERS_LOGIN_CA_CONTROLLER_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/controllers/login_ca_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_CONTROLLERS_VERIFY_PROFILE_CONTROLLER_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/controllers/verify_profile_controller.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_MODELS_AUTHEN_PROFILE_MODEL_AUTH_PROFILE_MODEL_SRC_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/models/authen_profile_model/auth_profile_model.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_MODELS_AUTHEN_PROFILE_MODEL_AUTH_PROFILE_REQUEST_MODEL_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/models/authen_profile_model/auth_profile_request_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_MODELS_AUTHEN_PROFILE_MODEL_AUTH_PROFILE_RESPONSE_MODEL_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/models/authen_profile_model/auth_profile_response_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_MODELS_LOGIN_CA_MODEL_LOGIN_CA_MODEL_SRC_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/models/login_ca_model/login_ca_model.src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_MODELS_LOGIN_CA_MODEL_LOGIN_CA_REQUEST_MODEL_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/models/login_ca_model/login_ca_request_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_MODELS_LOGIN_CA_MODEL_LOGIN_CA_REQUEST_MODEL_G_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/models/login_ca_model/login_ca_request_model.g.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_MODELS_LOGIN_CA_MODEL_LOGIN_CA_RESPONSE_MODEL_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/models/login_ca_model/login_ca_response_model.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_REPOSITORY_AUTH_PROFILE_REPOSITORY_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/repository/auth_profile_repository.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_REPOSITORY_LOGIN_CA_REPOSITORY_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/repository/login_ca_repository.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_VERIFY_PROFILE_CA_SRC_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/verify_profile_ca_src.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_VIEWS_AUTHENTICATION_GUIDE_PAGE_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/views/authentication_guide_page.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_VIEWS_AUTHENTICATION_GUIDE_VIEW_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/views/authentication_guide_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_VIEWS_LISTVIEW_PROFILE_VIEW_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/views/listview_profile_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_VIEWS_LOGIN_EASY_CA_VIEW_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/views/login_easy_ca_view.dart';

  static const String
      LIB_MODULES_AUTHENTICATION_KYC_VERIFY_PROFILE_CA_VIEWS_VERIFY_PROFILE_PAGE_DART =
      'lib/modules/authentication_kyc/verify_profile_ca/views/verify_profile_page.dart';

  static const String LIB_MODULES_HOME_COLLECTION_HOME_COLLECTION_DART =
      'lib/modules/home/collection/home_collection.dart';

  static const String LIB_MODULES_HOME_COLLECTION_HOME_CONST_DART =
      'lib/modules/home/collection/home_const.dart';

  static const String LIB_MODULES_HOME_CONTROLLERS_HOME_CONTROLLER_DART =
      'lib/modules/home/controllers/home_controller.dart';

  static const String LIB_MODULES_HOME_HOME_SRC_DART =
      'lib/modules/home/home.src.dart';

  static const String LIB_MODULES_HOME_VIEWS_BOTTOM_NAVIGATION_DART =
      'lib/modules/home/views/bottom_navigation.dart';

  static const String LIB_MODULES_HOME_VIEWS_HOME_PAGE_DART =
      'lib/modules/home/views/home_page.dart';

  static const String LIB_MODULES_LOGIN_CONTROLLERS_LOGIN_CONTROLLER_DART =
      'lib/modules/login/controllers/login_controller.dart';

  static const String LIB_MODULES_LOGIN_LOGIN_SRC_DART =
      'lib/modules/login/login.src.dart';

  static const String LIB_MODULES_LOGIN_MODEL_USER_INFO_MODEL_DART =
      'lib/modules/login/model/user_info_model.dart';

  static const String LIB_MODULES_LOGIN_VIEWS_LOGIN_PAGE_DART =
      'lib/modules/login/views/login_page.dart';

  static const String LIB_MODULES_LOGIN_VIEWS_LOGIN_VIEW_DART =
      'lib/modules/login/views/login_view.dart';

  static const String LIB_MODULES_MODULES_SRC_DART =
      'lib/modules/modules.src.dart';

  static const String LIB_MODULES_OTHER_OTHER_SRC_DART =
      'lib/modules/other/other.src.dart';

  static const String LIB_MODULES_OTHER_VIEWS_OTHER_PAGE_DART =
      'lib/modules/other/views/other_page.dart';

  static const String
      LIB_MODULES_OVERVIEW_CONTROLLERS_OVERVIEW_CONTROLLER_DART =
      'lib/modules/overview/controllers/overview_controller.dart';

  static const String LIB_MODULES_OVERVIEW_OVERVIEW_SRC_DART =
      'lib/modules/overview/overview.src.dart';

  static const String LIB_MODULES_OVERVIEW_VIEWS_OVERVIEW_PAGE_DART =
      'lib/modules/overview/views/overview_page.dart';

  static const String LIB_MODULES_OVERVIEW_VIEWS_OVERVIEW_VIEW_DART =
      'lib/modules/overview/views/overview_view.dart';

  static const String
      LIB_MODULES_PROVISION_CONTROLLERS_PROVISION_CONTROLLER_DART =
      'lib/modules/provision/controllers/provision_controller.dart';

  static const String LIB_MODULES_PROVISION_PROVISION_SRC_DART =
      'lib/modules/provision/provision.src.dart';

  static const String
      LIB_MODULES_PROVISION_REPOSITORY_PROVISION_REPOSITORY_DART =
      'lib/modules/provision/repository/provision_repository.dart';

  static const String LIB_MODULES_PROVISION_VIEWS_PROVISION_PAGE_DART =
      'lib/modules/provision/views/provision_page.dart';

  static const String LIB_MODULES_PROVISION_VIEWS_PROVISION_VIEW_DART =
      'lib/modules/provision/views/provision_view.dart';

  static const String
      LIB_MODULES_REGISTER_INFO_CONTROLLERS_REGISTER_INFO_CONTROLLER_DART =
      'lib/modules/register_info/controllers/register_info_controller.dart';

  static const String
      LIB_MODULES_REGISTER_INFO_MODEL_REGISTER_REQUEST_MODEL_DART =
      'lib/modules/register_info/model/register_request_model.dart';

  static const String LIB_MODULES_REGISTER_INFO_REGISTER_INFO_SRC_DART =
      'lib/modules/register_info/register_info.src.dart';

  static const String
      LIB_MODULES_REGISTER_INFO_REPOSITORY_REGISTER_REPOSITORY_DART =
      'lib/modules/register_info/repository/register_repository.dart';

  static const String LIB_MODULES_REGISTER_INFO_VIEWS_REGISTER_INFO_PAGE_DART =
      'lib/modules/register_info/views/register_info_page.dart';

  static const String LIB_MODULES_REGISTER_INFO_VIEWS_REGISTER_INFO_VIEW_DART =
      'lib/modules/register_info/views/register_info_view.dart';

  static const String LIB_MODULES_SDK_MODULES_EKYC_DART =
      'lib/modules/sdk/modules_ekyc.dart';

  static const String LIB_MODULES_SDK_SDK_SRC_DART =
      'lib/modules/sdk/sdk.src.dart';

  static const String LIB_MODULES_SDK_SDK_REQUEST_API_DART =
      'lib/modules/sdk/sdk_request_api.dart';

  static const String LIB_MODULES_SDK_SDK_REQUEST_MODEL_DART =
      'lib/modules/sdk/sdk_request_model.dart';

  static const String LIB_MODULES_SDK_SDK_RESPONSE_MODEL_DART =
      'lib/modules/sdk/sdk_response_model.dart';

  static const String LIB_MODULES_SPLASH_CONTROLLER_SPLASH_CONTROLLER_DART =
      'lib/modules/splash/controller/splash_controller.dart';

  static const String LIB_MODULES_SPLASH_SPLASH_SRC_DART =
      'lib/modules/splash/splash.src.dart';

  static const String LIB_MODULES_SPLASH_VIEW_SPLASH_PAGE_DART =
      'lib/modules/splash/view/splash_page.dart';

  static const String LIB_MODULES_SUPPORT_CONTROLLERS_SUPPORT_CONTROLLER_DART =
      'lib/modules/support/controllers/support_controller.dart';

  static const String LIB_MODULES_SUPPORT_MODEL_SUPPORT_MODEL_DART =
      'lib/modules/support/model/support_model.dart';

  static const String LIB_MODULES_SUPPORT_REPOSITORY_SUPPORT_REPOSITORY_DART =
      'lib/modules/support/repository/support_repository.dart';

  static const String LIB_MODULES_SUPPORT_SUPPORT_SRC_DART =
      'lib/modules/support/support.src.dart';

  static const String LIB_MODULES_SUPPORT_VIEWS_SUPPORT_PAGE_DART =
      'lib/modules/support/views/support_page.dart';

  static const String LIB_MODULES_SUPPORT_VIEWS_SUPPORT_VIEW_DART =
      'lib/modules/support/views/support_view.dart';

  static const String
      LIB_MODULES_USER_INFO_CONTROLLERS_USER_INFO_CONTROLLER_DART =
      'lib/modules/user_info/controllers/user_info_controller.dart';

  static const String LIB_MODULES_USER_INFO_USER_INFO_SRC_DART =
      'lib/modules/user_info/user_info.src.dart';

  static const String LIB_MODULES_USER_INFO_VALUE_USE_INFO_COLLECTION_DART =
      'lib/modules/user_info/value/use_info_collection.dart';

  static const String LIB_MODULES_USER_INFO_VIEWS_USER_INFO_PAGE_DART =
      'lib/modules/user_info/views/user_info_page.dart';

  static const String LIB_MODULES_USER_INFO_VIEWS_USER_INFO_VIEW_DART =
      'lib/modules/user_info/views/user_info_view.dart';

  static const String LIB_SHARES_BIOMETRIC_BIOMETRICS_DART =
      'lib/shares/biometric/biometrics.dart';

  static const String LIB_SHARES_FUNCTION_CHECK_SUPPORT_NFC_DART =
      'lib/shares/function/check_support_nfc.dart';

  static const String LIB_SHARES_FUNCTION_FUNCTION_SRC_DART =
      'lib/shares/function/function.src.dart';

  static const String LIB_SHARES_FUNCTION_LOGGER_DART =
      'lib/shares/function/logger.dart';

  static const String LIB_SHARES_FUNCTION_SAVEKEY_SECURE_DART =
      'lib/shares/function/savekey_secure.dart';

  static const String LIB_SHARES_MODEL_INPUT_INPUT_SRC_DART =
      'lib/shares/model/input/input.src.dart';

  static const String LIB_SHARES_MODEL_INPUT_INPUT_FORM_MODEL_DART =
      'lib/shares/model/input/input_form_model.dart';

  static const String LIB_SHARES_MODEL_INPUT_INPUT_LABEL_MODEL_DART =
      'lib/shares/model/input/input_label_model.dart';

  static const String LIB_SHARES_MODEL_MODEL_SRC_DART =
      'lib/shares/model/model.src.dart';

  static const String LIB_SHARES_MODEL_NUMBER_FORMAT_NUMBER_CONFIG_DART =
      'lib/shares/model/number_format/number_config.dart';

  static const String LIB_SHARES_PACKAGE_EXPORT_PACKAGE_DART =
      'lib/shares/package/export_package.dart';

  static const String LIB_SHARES_SHARES_SRC_DART = 'lib/shares/shares.src.dart';

  static const String
      LIB_SHARES_UTILS_CONVERTIMAGE_CAMERA_IMAGE_CONVERTER_DART =
      'lib/shares/utils/convertImage/camera_image_converter.dart';

  static const String LIB_SHARES_UTILS_CURRENCY_CURRENCY_UTILS_DART =
      'lib/shares/utils/currency/currency_utils.dart';

  static const String LIB_SHARES_UTILS_DEVICE_DEVICE_UTILS_DART =
      'lib/shares/utils/device/device_utils.dart';

  static const String LIB_SHARES_UTILS_DEVICE_RATIO_SCREEN_DART =
      'lib/shares/utils/device/ratio_screen.dart';

  static const String LIB_SHARES_UTILS_FORMATTER_COMMA_FOMATTER_DART =
      'lib/shares/utils/formatter/comma_fomatter.dart';

  static const String LIB_SHARES_UTILS_FORMATTER_FORMATTER_SRC_DART =
      'lib/shares/utils/formatter/formatter.src.dart';

  static const String LIB_SHARES_UTILS_FORMATTER_FORMATTER_ENUM_DART =
      'lib/shares/utils/formatter/formatter_enum.dart';

  static const String LIB_SHARES_UTILS_FORMATTER_FORMATTER_UTILS_DART =
      'lib/shares/utils/formatter/formatter_utils.dart';

  static const String LIB_SHARES_UTILS_FORMATTER_INPUT_FORMATTER_ENUM_DART =
      'lib/shares/utils/formatter/input_formatter_enum.dart';

  static const String LIB_SHARES_UTILS_FORMATTER_LIMIT_TEXTFIELD_DART =
      'lib/shares/utils/formatter/limit_textfield.dart';

  static const String LIB_SHARES_UTILS_FORMATTER_NUMBERIC_TEXT_FORMATTER_DART =
      'lib/shares/utils/formatter/numberic_text_formatter.dart';

  static const String LIB_SHARES_UTILS_KEY_BOARD_KEYBOARD_DART =
      'lib/shares/utils/key_board/keyboard.dart';

  static const String LIB_SHARES_UTILS_LOG_DIO_LOG_DART =
      'lib/shares/utils/log/dio_log.dart';

  static const String LIB_SHARES_UTILS_PERMISSION_PERMISSION_DART =
      'lib/shares/utils/permission/permission.dart';

  static const String LIB_SHARES_UTILS_SDK_CREATE_PARARM_DART =
      'lib/shares/utils/sdk/create_pararm.dart';

  static const String LIB_SHARES_UTILS_SDK_SDK_UTILS_SRC_DART =
      'lib/shares/utils/sdk/sdk_utils.src.dart';

  static const String LIB_SHARES_UTILS_SDK_VERIFICATION_UTILS_DART =
      'lib/shares/utils/sdk/verification_utils.dart';

  static const String LIB_SHARES_UTILS_TEXT2SPEECH_BASE_TTS_DART =
      'lib/shares/utils/text2speech/base_tts.dart';

  static const String LIB_SHARES_UTILS_TEXT2SPEECH_OFFLINE_TTS_DART =
      'lib/shares/utils/text2speech/offline_tts.dart';

  static const String LIB_SHARES_UTILS_TEXT2SPEECH_ONLINE_TTS_DART =
      'lib/shares/utils/text2speech/online_tts.dart';

  static const String LIB_SHARES_UTILS_TEXT2SPEECH_TEXT2SPEECH_SRC_DART =
      'lib/shares/utils/text2speech/text2speech.src.dart';

  static const String LIB_SHARES_UTILS_TEXT2SPEECH_TTS_MANAGER_DART =
      'lib/shares/utils/text2speech/tts_manager.dart';

  static const String LIB_SHARES_UTILS_TIME_DATE_UTILS_DART =
      'lib/shares/utils/time/date_utils.dart';

  static const String LIB_SHARES_UTILS_UTILS_SRC_DART =
      'lib/shares/utils/utils.src.dart';

  static const String LIB_SHARES_UTILS_VALIDATE_VALIDATE_DART =
      'lib/shares/utils/validate/validate.dart';

  static const String LIB_SHARES_WIDGETS_APP_BAR_APP_BAR_SRC_DART =
      'lib/shares/widgets/app_bar/app_bar.src.dart';

  static const String LIB_SHARES_WIDGETS_APP_BAR_BACKGROUND_APP_BAR_DART =
      'lib/shares/widgets/app_bar/background_app_bar.dart';

  static const String LIB_SHARES_WIDGETS_BOTTOM_SHEET_BASE_BOTTOM_SHEET_DART =
      'lib/shares/widgets/bottom_sheet/base_bottom_sheet.dart';

  static const String
      LIB_SHARES_WIDGETS_BOTTOM_SHEET_BASE_BOTTOM_SHEET_OTHER_DART =
      'lib/shares/widgets/bottom_sheet/base_bottom_sheet_other.dart';

  static const String LIB_SHARES_WIDGETS_BOTTOM_SHEET_BOTTOM_SHEET_SRC_DART =
      'lib/shares/widgets/bottom_sheet/bottom_sheet.src.dart';

  static const String
      LIB_SHARES_WIDGETS_BOTTOM_SHEET_BOTTOM_SHEET_CHECK_NFC_DART =
      'lib/shares/widgets/bottom_sheet/bottom_sheet_check_nfc.dart';

  static const String LIB_SHARES_WIDGETS_BUTTON_BUTTON_SRC_DART =
      'lib/shares/widgets/button/button.src.dart';

  static const String LIB_SHARES_WIDGETS_BUTTON_BUTTON_UTILS_DART =
      'lib/shares/widgets/button/button_utils.dart';

  static const String LIB_SHARES_WIDGETS_DIALOG_DIALOG_SRC_DART =
      'lib/shares/widgets/dialog/dialog.src.dart';

  static const String LIB_SHARES_WIDGETS_DIALOG_DIALOG_UTILS_DART =
      'lib/shares/widgets/dialog/dialog_utils.dart';

  static const String LIB_SHARES_WIDGETS_DROPDOWN_DROPDOWN_BASE_DART =
      'lib/shares/widgets/dropdown/dropdown_base.dart';

  static const String LIB_SHARES_WIDGETS_FORM_BASE_FORM_LOGIN_DART =
      'lib/shares/widgets/form/base_form_login.dart';

  static const String LIB_SHARES_WIDGETS_FORM_FORM_OVERVIEW_DART =
      'lib/shares/widgets/form/form_overview.dart';

  static const String LIB_SHARES_WIDGETS_IMAGE_APP_IMAGE_APP_SRC_DART =
      'lib/shares/widgets/image_app/image_app.src.dart';

  static const String LIB_SHARES_WIDGETS_IMAGE_APP_IMAGE_WIDGET_DART =
      'lib/shares/widgets/image_app/image_widget.dart';

  static const String LIB_SHARES_WIDGETS_IMAGE_NETWORK_IMAGE_NETWORK_DART =
      'lib/shares/widgets/image_network/image_network.dart';

  static const String LIB_SHARES_WIDGETS_IMAGE_NETWORK_IMAGE_NETWORK_SRC_DART =
      'lib/shares/widgets/image_network/image_network.src.dart';

  static const String
      LIB_SHARES_WIDGETS_IMAGE_NETWORK_IMAGE_NETWORK_MODEL_DART =
      'lib/shares/widgets/image_network/image_network_model.dart';

  static const String LIB_SHARES_WIDGETS_INPUT_INPUT_SRC_DART =
      'lib/shares/widgets/input/input.src.dart';

  static const String LIB_SHARES_WIDGETS_INPUT_INPUT_LABEL_DART =
      'lib/shares/widgets/input/input_label.dart';

  static const String LIB_SHARES_WIDGETS_INPUT_INPUT_TEXT_DART =
      'lib/shares/widgets/input/input_text.dart';

  static const String LIB_SHARES_WIDGETS_SHOW_NOTI_FLUSHBAR_WIDGET_DART =
      'lib/shares/widgets/show_noti/flushbar_widget.dart';

  static const String LIB_SHARES_WIDGETS_SHOW_NOTI_SHOW_NOTI_SRC_DART =
      'lib/shares/widgets/show_noti/show_noti.src.dart';

  static const String LIB_SHARES_WIDGETS_SIZED_BOX_SIZED_BOX_DART =
      'lib/shares/widgets/sized_box/sized_box.dart';

  static const String LIB_SHARES_WIDGETS_TEXT_FONT_STYLE_DART =
      'lib/shares/widgets/text/font_style.dart';

  static const String LIB_SHARES_WIDGETS_TEXT_TEXT_UTILS_DART =
      'lib/shares/widgets/text/text_utils.dart';

  static const String LIB_SHARES_WIDGETS_UTILS_WIDGET_UTILS_WIDGET_DART =
      'lib/shares/widgets/utils_widget/utils_widget.dart';

  static const String LIB_SHARES_WIDGETS_UTILS_WIDGET_UTILS_WIDGET_SRC_DART =
      'lib/shares/widgets/utils_widget/utils_widget.src.dart';

  static const String LIB_SHARES_WIDGETS_WIDGETS_SRC_DART =
      'lib/shares/widgets/widgets.src.dart';
}
